import Head from 'next/head'
import styles from '../styles/Home.module.css'
import LayoutApp from '../components/Layout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tra cứu thu nhập | Login </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home</h1>
    </div>
  )
}
