import React, {useEffect, useState} from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { Button, Result, Spin   } from 'antd';
import Login from './login'
import ThuNhapThang from './thunhapthang'

const Home = () => {
  const router = useRouter()
  const [isLogin, setIsLogin] = useState(false)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(()=>{
    setTimeout(() => {
      setIsLogin(window.localStorage.getItem('rTokenTracuu') !== null ? true : false)
      setIsLoading(false)
      }, 500);
    }, []);

  function onClick(){
    router.push('/thunhapthang')
  }

  function onClickLogin(){
    router.push('/login')
  }
  if(isLogin){
    return (
      <div className={styles.container}>
        <Head>
          <title>Tra cứu thu nhập</title>
          <meta name="description" content="Tra cứu thu nhập" />
          <link rel="icon" href="/favicon-16x16.png" />
        </Head>
        {onClick()}
      </div>
    )} 
    return(
      <>
        <Head>
          <title>Tra cứu thu nhập </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon-16x16.png" />
        </Head>
        {isLoading ? <Spin  size="large"/> :
        
        <Result
          status="403"
          title=""
          subTitle="Bạn chưa đăng nhập. Vui lòng đăng nhập"
          extra={<Button onClick={onClickLogin} type="primary">Đăng nhập</Button>}
        />  
        }
      </>
    )
}

export default Home;
Home.getLayout = function PageLayout(page) {
  return <>{page}</>
}
