import React from "react";
import Head from 'next/head'
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined
} from '@ant-design/icons';
import { Layout } from 'antd';
const { Header, Content } = Layout;
import Navbar from "../Navbar";

const HeaderApp = (props) => {
  const {collapsed} = props
  return (
    <>
       <Head>
        <title>Tra cứu thu nhập</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
          className="site-layout-background"
          style={{
            padding:0,
            background: '#fff'
          }}
        >
          {React.createElement(collapsed ? MenuUnfoldOutlined : MenuFoldOutlined, {
            style:{padding: '0 24px',
              fontSize: '18px',
              lineHeight: '64px',
              cursor: 'pointer'} ,
            onClick: () => setCollapsed(!collapsed),
          })}
        </Header>
    </>
  );
}

export default HeaderApp;