import React, {useState, useEffect} from "react";
import Head from 'next/head'
import axios from 'axios'
import { Button, Select, Space, Input  } from 'antd';
import {HStack, VStack, Wrap, Text} from  '@chakra-ui/react';
import Item from "../../components/Item";
import styles from './index.module.css'
import ItemAll from "../../components/Item/ItemAll";
const { Option } = Select;


const ThuNhapThang = () =>{
  const [data, setData] = useState()
  const [thangBK, setThangBK] = useState()
  const [namBK, setNamBK] = useState()
  const [loading, setLoading] = useState(false);
  const [maNV, setMaNV] = useState('')
  const today = new Date();
  const defaultYear = today.getFullYear()
  const defaultMonth = today.getMonth()
  
  useEffect(()=>{
    setMaNV(window.localStorage.getItem('idTracuu'))
  }, [])

  function handleChangeThang (value)  {
    setThangBK(value)
    setLoading(true)
  };

  useEffect(()=>{
    setNamBK(defaultYear)
    setThangBK(defaultMonth)
  }, [defaultYear, defaultMonth])
  
  useEffect(() => {
    const timer = setTimeout(() => {
      loadThuNhapThang()
      setLoading(false)
    },2000);
    return () => clearTimeout(timer);
  }, [thangBK]);

  function handleChangeName (event)  {
    setNamBK(event.target.value)
  };

  async function loadThuNhapThang(){
    return await axios
      .post('http://localhost:3001/thunhapthang', {manv: maNV, thangBK :thangBK, namBK: namBK})
      .then((res) => {
        const result = {
          status: res.data.status,
          data: res.data.result.recordset,
        }
        setData(res.data.result.recordsets)
        return(result)
      })
      .catch(function (error) {
        // handle error
        console.log(error.response)
      })
  }
  return(
    <>
      <Head>
        <title>Tra cứu thu nhập hàng tháng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-16x16.png" />
      </Head>
      <VStack>
        <Text fontSize={"2xl"} fontWeight="bold" marginBottom={"2rem"} color ={"#38b2ac"}>Tra cứu thông tin thu nhập hàng tháng</Text>
        <HStack style ={{marginBottom:"1rem !important"}} alignItems={"center"} spacing={10}>
          <HStack>
            <Text>Tháng:</Text>
            <Select defaultValue={defaultMonth.toString()} style={{ width: 120 }} onChange={handleChangeThang}>
              <Option value="all">Chọn tất cả</Option>
              <Option value="1">Tháng 1</Option>
              <Option value="2">Tháng 2</Option>
              <Option value="3">Tháng 3</Option>
              <Option value="4">Tháng 4</Option>
              <Option value="5">Tháng 5</Option>
              <Option value="6">Tháng 6</Option>
              <Option value="7">Tháng 7</Option>
              <Option value="8">Tháng 8</Option>
              <Option value="9">Tháng 9</Option>
              <Option value="10">Tháng 10</Option>
              <Option value="11">Tháng 11</Option>
              <Option value="12">Tháng 12</Option>
            </Select>
          </HStack>
          <HStack>
            <Text>Năm:</Text>
            <Input defaultValue={defaultYear}  className={styles.inputNam} placeholder="Năm" onChange={handleChangeName}  />;
          </HStack>
          <Button type="primary" onClick={loadThuNhapThang}>Lọc dữ liệu</Button>  
        </HStack>
        {data?.length === 1 ?
          (<Wrap justify='center'>
            <Item title ={`Thu nhập tháng ${thangBK} năm ${namBK}`} loading ={loading} thang ={thangBK} nam ={namBK} data ={data[0]} />
          </Wrap>)
          :(
            <ItemAll loading ={loading} nam ={namBK} data ={data} />
          )
          }
      </VStack>
    </> 
  )
}

export default ThuNhapThang;