import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import axios from 'axios'
import {VStack} from '@chakra-ui/react'
import { Button, Checkbox, Form, Input, Typography, Alert  } from 'antd';
import styles from './index.module.css'

const { Paragraph , Title } = Typography;

const Login = () => {
  const [userName, setUserName] = useState()
  const [email, setEmail] = useState()
  const [password, setPassword] = useState()
  const [statusCode, setStatusCode] = useState()
  const [error,setError] = useState(false)
  const [remember,setRemember] = useState(false)
  const [errorText,setErrorText] = useState('')
  const router = useRouter()

  async function submitLogin(data){
    return await axios
    .post('http://localhost:3001/user/login', {email: data.email, password: data.password})
    .then((res) => {
      setEmail(data.email)
      setPassword(data.password)
      setUserName(res.data.userName)
      setStatusCode(res.status)
      setError(false)
      if(data.remember){
        window.localStorage.setItem('fullNameTracuu', res.data.userName)
        window.localStorage.setItem('emailTracuu', data.email)
        window.localStorage.setItem('passwordTracuu', data.password)
        window.localStorage.setItem('rememberTracuu', JSON.stringify(data.remember))
      }
      
      router.push('/thunhapthang')
      return(result)
    })
    .catch(function (error) {
      // handle error
      setError(true)
      setErrorText(error?.response?.data.message)
    })
  }
  useEffect(() => {
    // Prefetch the dashboard page
    router.prefetch('/thunhapthang')
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Tra cứu thu nhập | Login </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.loginSection}>
        {/* <Avatar size={{sx: 64, sm: 64, md: 64, lg: 80, xl:80, xxl: 80}} src ={'./logo.jpg'} />
        */}
        <div style={{background: '#163764', marginBottom: '1rem', borderRadius: '5px'}}>
        <a
            href="https://ufm.edu.vn/"
            target="_blank"
            rel="noopener noreferrer"
          >
          <img src='./logo4.png'/>
          </a>
        </div>
        <Title level={2}>ĐĂNG NHẬP</Title>
        <Paragraph><b>HỆ THỐNG TRA CỨU THÔNG TIN THU NHẬP</b></Paragraph >
        <VStack margin={"2em"} alignItems={"center"}>
          <Form
              name="basic"
              labelCol={{
                span: 8,
              }}
              wrapperCol={{
                span: 20,
              }}
              initialValues={{
                remember: true,
              }}
              // onFinish={onFinish}
              // onFinishFailed={onFinishFailed}
              autoComplete="off"
              onFinish={submitLogin}
            >
              <Form.Item
                label="Email: "
                name="email"
                rules={[
                  {
                    required: true,
                    message: 'Vui lòng nhập Email!',
                    type:'email'
                  },
                ]}
              >
                <Input />
              </Form.Item>

              <Form.Item
                label="Mật khẩu: "
                name="password"
                rules={[
                  {
                    required: true,
                    message: 'Vui lòng nhập mật khẩu!',
                  },
                ]}
              >
                <Input.Password />
              </Form.Item>

              <Form.Item
                name="remember"
                valuePropName="checked"
                wrapperCol={{
                  offset: 8,
                  span: 16,
                }}
              >
                <Checkbox>Nhớ mật khẩu</Checkbox>
              </Form.Item>

              <Form.Item
                wrapperCol={{
                  offset: 4,
                  span: 16,
                }}
              >
                <Button type="primary" block htmlType="submit">
                  Đăng nhập
                </Button>
              </Form.Item>
            </Form>
          </VStack>
        </section>
      </main>
      {error && <Alert
        message="Lỗi đăng nhập"
        description={errorText}
        type={error ? "error": 'success'}
      />}
      <footer className={styles.footer}>
        <a
          href="https://phongcntt.ufm.edu.vn/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Coppyright by:{' '} © 2022 Phòng Công nghệ thông tin
        </a>
      </footer>
    </div>
   );
}

export default Login;
Login.getLayout = function PageLayout(page) {
  return <>{page}</>
}