import Ract from 'react'
import Head from 'next/head'
import Icon, { LockOutlined } from '@ant-design/icons';
import { Button, Checkbox, Form, Input, Typography, Avatar  } from 'antd';
const { Paragraph , Title } = Typography;
import logo from '../../public/logo.jpg'
import styles from './index.module.css'

function Login() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tra cứu thu nhập | Login </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.loginSection}>
        {/* <Avatar size={{sx: 64, sm: 64, md: 64, lg: 80, xl:80, xxl: 80}} src ={'./logo.jpg'} />
        */}
        <div style={{background: '#163764', marginBottom: '1rem', borderRadius: '5px'}}>
        <a
            href="https://ufm.edu.vn/"
            target="_blank"
            rel="noopener noreferrer"
          >
          <img src='./logo4.png'/>
          </a>
        </div>
        <Title level={2}>ĐĂNG NHẬP</Title>
        <Paragraph><b>HỆ THỐNG TRA CỨU THÔNG TIN THU NHẬP</b></Paragraph >
        <div style={{marginTop: '2em'}}>
          <Form
              name="basic"
              labelCol={{
                span: 10,
              }}
              wrapperCol={{
                span: 16,
              }}
              initialValues={{
                remember: true,
              }}
              // onFinish={onFinish}
              // onFinishFailed={onFinishFailed}
              autoComplete="off"
            >
              <Form.Item
                label="Tên đăng nhập: "
                name="username"
                rules={[
                  {
                    required: true,
                    message: 'Vui lòng nhập tên đăng nhập!',
                  },
                ]}
              >
                <Input />
              </Form.Item>

              <Form.Item
                label="Mật khẩu: "
                name="password"
                rules={[
                  {
                    required: true,
                    message: 'Vui lòng nhập mật khẩu!',
                  },
                ]}
              >
                <Input.Password />
              </Form.Item>

              <Form.Item
                name="remember"
                valuePropName="checked"
                wrapperCol={{
                  offset: 8,
                  span: 16,
                }}
              >
                <Checkbox>Remember me</Checkbox>
              </Form.Item>

              <Form.Item
                wrapperCol={{
                  offset: 4,
                  span: 16,
                }}
              >
                <Button type="primary" block htmlType="submit">
                  Đăng nhập
                </Button>
              </Form.Item>
            </Form>
          </div>
        </section>
      </main>
      
      <footer className={styles.footer}>
          <a
            href="https://phongkhtc.ufm.edu.vn/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by:{' '} © 2022 Phòng Kế hoạch - Tài chính
          </a>
        </footer>
    </div>
   );
}

export default Login;
Login.getLayout = function PageLayout(page) {
  return <>{page}</>
}