import React, {useState} from "react";
import Head from 'next/head'
import { VStack, Text } from "@chakra-ui/react";
import {Descriptions, Button, Form, Input, Modal }from 'antd';
import styles from './index.module.css'

const Profile =(props) =>{
  const [openModal, setOpenModal] = useState(false)
  const [openModalChangeEmail, setOpenModalChangeEmail] = useState(false)

  function toogleModalForm(){
    setOpenModal(!openModal)
  }
  function toogleModalFormChangeEmail(){
    setOpenModalChangeEmail(!openModalChangeEmail)
  }
  return(
    <>
      <Head>
        <title>Trang cá nhân</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-16x16.png" />
      </Head>
      <VStack>
        <Text fontSize={{md:"2xl", lg:'2xl', sm:'xl'}} fontWeight="bold" marginBottom={"2rem"} color ={"#38b2ac"}>Trang thông tin cá nhân</Text>
          <Descriptions  layout="vertical" bordered>
            <Descriptions.Item label="Mã nhân viên">Zhou Maomao</Descriptions.Item>
            <Descriptions.Item label="Họ và Tên">Zhou Maomao</Descriptions.Item>
            <Descriptions.Item label="Đơn vị">Xihu District, Hangzhou, Zhejiang, China</Descriptions.Item>
            <Descriptions.Item label="Điện thoại">Hangzhou, Zhejiang</Descriptions.Item>
            <Descriptions.Item label="Email">Hangzhou, Zhejiang{'    '}<Button onClick={toogleModalFormChangeEmail} type="link">Cập nhật email</Button></Descriptions.Item>
          </Descriptions>
          <Button type="primary" onClick={toogleModalForm}>Đổi mật khẩu</Button>
      </VStack>
      <Modal
        visible={openModal}
        title="Đổi mật khẩu"
        // onOk={handleOk}
        onCancel={toogleModalForm}
        footer={[
          <Button key="back" onClick={toogleModalForm}>
            Thoát
          </Button>,
          <Button type="primary">Đổi mật khẩu</Button>,
        ]}
      >
      <Form
          name="basic"
          labelCol={{
            span: 8,
          }}
          wrapperCol={{
            span: 20,
          }}
          initialValues={{
            remember: true,
          }}
          autoComplete="off"
          // onFinish={submitLogin}
        >
          <Form.Item
            label="Mật khẩu mới: "
            name="newPassword"
            rules={[
              {
                required: true
              },
            ]}
          >
            <Input.Password />
          </Form.Item>

          <Form.Item
            label="Nhập lại mật khẩu: "
            name="repeatPassword"
            rules={[
              {
                required: true,
              },
            ]}
          >
            <Input.Password />
          </Form.Item>
        </Form>
      </Modal>
      {/* Modal đổi email */}
      <Modal
        visible={openModalChangeEmail}
        title="Cập nhật email"
        // onOk={handleOk}
        onCancel={toogleModalFormChangeEmail}
        footer={[
          <Button key="back" onClick={toogleModalFormChangeEmail}>
            Thoát
          </Button>,
          <Button type="primary" danger>Cập nhật</Button>,
        ]}
      >
      <Form
          name="basic"
          labelCol={{
            span: 8,
          }}
          wrapperCol={{
            span: 20,
          }}
          initialValues={{
            remember: true,
          }}
          autoComplete="off"
          // onFinish={submitLogin}
        >
          <Form.Item
            label="Email hiện tại: "
            name="email"
            rules={[
              {
                required: true,
                message: 'Vui lòng nhập đúng định dạng Email!',
                type:'email'
              },
            ]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            label="Email mới: "
            name="emailNew"
            rules={[
              {
                required: true,
                message: 'Vui lòng nhập đúng định dạng Email! ',
                type:'email'
              },
            ]}
          >
            <Input />
          </Form.Item>
        </Form>
      </Modal>
    </>
  )
}

export default Profile;