import React, {useState,} from "react";
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Document, Page } from 'react-pdf';
import { pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/legacy/build/pdf.worker.min.js`;
import { VStack, Text } from "@chakra-ui/react";
import { BackTop } from 'antd';

const Help = (props) =>{
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  return(
    <>
      <Head>
        <title>Trang cá nhân</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-16x16.png" />
      </Head>
      <BackTop />
      <VStack alignItems={"center"}>
      
        <Document file="./HDSD.pdf" onLoadSuccess={onDocumentLoadSuccess}>
        {Array.from(new Array(numPages), (el, index) => (
                <Page key={`page_${index + 1}`} pageNumber={index + 1} />
              ))} 
        </Document>
      </VStack>
      
    </>
  )
}


export default Help;
Help.getLayout = function PageLayout(page) {
  return <>{page}</>
}